### ISSUE TITLE
在 webpack4 下报错

### ISSUE THREAD

**Issue by zoumiaojiang** [searchfe/sw-register-webpack-plugin#20]
错误如下：
![image](https://user-images.githubusercontent.com/26755049/54656075-3bafbe80-4aff-11e9-95e5-c19ecb4ae0d1.png)

sw-register-webpack-plugin 版本 1.0.21
webpack 版本 4.29.6
babel版本  ^7.3.4

**Comment by qq282126990** [comment]
升级 babel :
![image](https://user-images.githubusercontent.com/26755049/54911751-1ae5cf80-4f2a-11e9-87e3-e910c0755bcc.png)
使用新 api
![image](https://user-images.githubusercontent.com/26755049/54911807-3d77e880-4f2a-11e9-84ec-c69265f27b96.png)

**Comment by zoumiaojiang** [comment]
感谢给出方案，辛苦提交个 pull request?

**Comment by qq282126990** [comment]
以提 pull request

**Comment by endday** [comment]
他已经发了了request了，大佬求速度合并代码啊，等着用啊
@zoumiaojiang

**Comment by qq282126990** [comment]
https://github.com/qq282126990/webpack/blob/f0e0c588ccd776bdb1031466e248334889001738/.ivue/sw-register-webpack-plugin.js        可到这里下载

**Comment by zoumiaojiang** [comment]
问题已修复，最新版的 1.0.22 版本已解决
