### ISSUE TITLE
【建议】建议增加一个 ignore 配置项

### ISSUE THREAD

**Issue by clark-t** [searchfe/sw-register-webpack-plugin#3]
目前 sw-register-webpack-plugin 会默认给所有 .html 的文件注入 service worker 的注册代码，在项目当中并不是所有的 html 文件都需要注册 service worker 的，尤其是一些作为校验文件的 html 如果被污染，就出问题了，因此建议增加一个 ignore 配置项，最好能够支持正则或者回调函数的文件匹配方式。

**Comment by zoumiaojiang** [comment]
已经在 1.0.11 版本中新增 includes 和 excludes 的配置
