### ISSUE TITLE
sw-register.js注册service-worker.js时，找不到service-worker.js文件

### ISSUE THREAD

**Issue by Coderkobe** [searchfe/sw-register-webpack-plugin#8]
项目文件关系
![image](https://user-images.githubusercontent.com/18484020/36955528-f614bd88-2063-11e8-9e66-1d91f961014f.png)
通过插件，页面插入本地sw-register.js文件。路径为‘http://localhost:8080/sw-register.js?v=1520218536996‘。
![image](https://user-images.githubusercontent.com/18484020/36955576-3de55fd2-2064-11e8-87a3-be1c4771cfce.png)
当在sw-register.js注册service-worker.js文件时，文件找不到。

**Comment by zoumiaojiang** [comment]
能看一下浏览器的报错详细信息吗？或者也有可能因为 localhost 的 service worker 互相影响的风险太高，可能是 /service-worker.js 文件被之前的 service worker 给缓存了，你可以试着注销你 localhost 域下的 service worker 试试看。

**Comment by Coderkobe** [comment]
![image](https://user-images.githubusercontent.com/18484020/36967870-de3901be-209b-11e8-86db-77924d90ad41.png)
我注销了，然后刷新。并没有什么效果。
webpack脚手架执行build时，发现sw-register.js文件可以build出来。service-worker.js文件不可以。这两个文件都是/目录下的，register可以，service-worker.js不可以。其实就是执行
![image](https://user-images.githubusercontent.com/18484020/36967985-2d68d0c0-209c-11e8-89e5-1dba716f4a28.png)有问题，或者脚手架的问题。

**Comment by zoumiaojiang** [comment]
`service-worker.js` 是需要自己维护的，你这个 `/service-worker.js` 看起来没有被路由配置到，所以才 404 了，不是说引入了这个插件就能构建出 `service-worker.js` 或者让 `service-worker.js` 可访问，这些都是要自行额外处理的，这个插件只会将已经提供的并且可访问的 `service-worker.js` 注册到站点里。
